# Generated by Django 3.1 on 2020-09-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('area', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=10)),
                ('list_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
