# Generated by Django 3.1 on 2020-09-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_datastatus_stocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='list_date',
            field=models.CharField(default=19900101, max_length=10),
            preserve_default=False,
        ),
    ]
