# Generated by Django 3.1 on 2020-09-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200906_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocklist',
        ),
    ]
