# Generated by Django 3.1 on 2020-10-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_delete_stocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stocks',
            field=models.TextField(default=''),
        ),
    ]
